# netlify.toml

[build]
  # This is the folder that contains your website's files (index.html, etc.)
  publish = "public"
  
  # This is the folder where Netlify will find your serverless functions
  functions = "netlify/functions"
